# 配置数据源
spring:
  datasource:
    username: root
    password: Hufei169357@
    url: jdbc:mysql://localhost:3306/springboot_netty?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置redis
  redis:
    port: 6379
    host: localhost
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    timeout: 10s

mybatis-plus:
  # mapper文件的位置
  mapper-locations: classpath:mapper/*.xml
  # pojo所在的目录
  type-aliases-package: com.feige.pojo
  #逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 配置日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl